config/routes.rb
Rails.application.routes.draw do
  # get 'contact/index'
  # get 'home/index'
  root to: 'rooms#index'
  resources :rooms
  resources :contact
  resources :maps
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Demande d'informations pour Maison Esperluette",
      :to => "lucille.james00@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/map.rb
class Map < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, presence: true
  validates :address, presence: true
end

app/models/room.rb
class Room < ApplicationRecord

	validates :name, presence: true
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

around_action :switch_locale

  def switch_locale(&action)
  	locale = params[:locale] || I18n.default_locale
  	I18n.with_locale(locale, &action)
   end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	skip_before_action :verify_authenticity_token
  def index
    @contact = Contact.new(params[:contact])
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        # re-initialize Contact object for cleared form
        @contact = Contact.new
        format.html { render 'index'}
        format.js   { flash.now[:success] = @message = "Merci pour votre message. Nous revenons vers vous au plus vite." }
      else
        format.html { render 'index' }
        format.js   { flash.now[:error] = @message = "Le message n'a pas pu être envoyé" }
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index

    @maps = Map.all

    @markers = @maps.geocoded.map do |map|
      {
        lat: map.latitude,
        lng: map.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { map: map })
      }
    end
  end

  def show
    @map = Map.find(params[:id])
  end

  def new
    @map = Map.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
  end

  def new
    @room = Room.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/contact/_contact_form.en.html.erb
<div class="contact_container d-flex flex-column justify-content-center align-items-center mr-3 ml-3 mt-3">
  <div class="contact_details">


    <p class='mb-5'>For more information, or any enquiry about the Bed&Breakfast, get in our touch with us today. Simply fill out the form below, or give us a call.<br>Please note, sending this enquiry does not confirm availability or make any commitment at this stage.</p>

    <h4>Phone</h4>
    <p class='mb-5'>+336.30.89.59.82</p>

    <h4>Get in touch</h4>  
  </div>

  <div class="form_container">
    <%= form_for @contact, url: contact_index_path, remote: true do |f| %>
    <div class="form-group">
      <%= f.label :name %></br>
      <%= f.text_field  :name, required: true, class: "form-group" %></br>

      <%= f.label :email %></br>

      <%= f.text_field :email, required: true, class: "form-group" %></br>

      <%= f.label :message %></br>
      <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "form-group",
          placeholder: "Send a message to the owner"%></br>

      <div class= "hidden">
        <%= f.label :nickname %>
        <%= f.text_field :nickname, placeholder: 'Do not fill out that field' %>
      </div>

      <%= f.submit 'Send', class: 'btn mb-5' %>
<!--       <#% if @contact.deliver %>
        <p>Merci</p>
      <#% else  %>
        <p>Le message n'a pas pu être envoyé</p>
      <#% end %> -->
    </div>
  <% end %>
  </div>
</div>


  <div class="col-md-6" id="flash-message">
    <%= render 'flash' %>
  </div>

app/views/contact/_contact_form.fr.html.erb
<div class="contact_container d-flex flex-column justify-content-center align-items-center mr-3 ml-3 mt-3">
  <div class="contact_details">


    <p class='mb-5'>Vous souhaitez connaître les dates de réservation disponibles ? Des questions sur les gîtes ?<br>N'hésitez pas à nous contacter !</p>

    <h4>Par téléphone</h4>
    <p class='mb-5'>06.30.89.59.82</p>

    <h4>Par mail</h4>  
  </div>

  <div class="form_container">
    <%= form_for @contact, url: contact_index_path, remote: true do |f| %>
    <div class="form-group">
      <%= f.label :nom %></br>
      <%= f.text_field  :name, required: true, class: "form-group" %></br>

      <%= f.label :email %></br>

      <%= f.text_field :email, required: true, class: "form-group" %></br>

      <%= f.label :message %></br>
      <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "form-group",
          placeholder: "Envoyez un message au propriétaire du gîte."%></br>

      <div class= "hidden">
        <%= f.label :nickname %>
        <%= f.text_field :nickname, placeholder: 'Ne pas remplir ce champ!' %>
      </div>

      <%= f.submit 'Envoyer', class: 'btn mb-5' %>
<!--       <#% if @contact.deliver %>
        <p>Merci</p>
      <#% else  %>
        <p>Le message n'a pas pu être envoyé</p>
      <#% end %> -->
    </div>
  <% end %>
  </div>
</div>


  <div class="col-md-6" id="flash-message">
    <%= render 'flash' %>
  </div>

app/views/contact/_contact_form.html.erb
<div class="contact_container d-flex flex-column justify-content-center align-items-center mr-3 ml-3 mt-3">
  <div class="contact_details">


    <p class='mb-5'>Vous souhaitez connaître les dates de réservation disponibles ? Des questions sur les gîtes ?<br>N'hésitez pas à nous contacter !</p>

    <h4>Par téléphone</h4>
    <p class='mb-5'>06.30.89.59.82</p>

    <h4>Par mail</h4>  
  </div>

  <div class="form_container">
    <%= form_for @contact, url: contact_index_path, remote: true do |f| %>
    <div class="form-group">
      <%= f.label :name %></br>
      <%= f.text_field  :name, required: true, class: "form-group" %></br>

      <%= f.label :email %></br>

      <%= f.text_field :email, required: true, class: "form-group" %></br>

      <%= f.label :message %></br>
      <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "form-group",
          placeholder: "Envoyez un message au propriétaire du gîte.Send a message to the owner"%></br>

      <div class= "hidden">
        <%= f.label :nickname %>
        <%= f.text_field :nickname, placeholder: 'Ne pas remplir ce champ!' %>
      </div>

      <%= f.submit 'Envoyer', class: 'btn mb-5' %>
<!--       <#% if @contact.deliver %>
        <p>Merci</p>
      <#% else  %>
        <p>Le message n'a pas pu être envoyé</p>
      <#% end %> -->
    </div>
  <% end %>
  </div>
</div>


  <div class="col-md-6" id="flash-message">
    <%= render 'flash' %>
  </div>

app/views/contact/_flash.html.erb
<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/contact/_sidebar.en.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">

  <%= link_to root_path(locale: :en), class: "navbar-brand" do %>
    <%= image_tag "logo-white2.png", class: 'logo' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Contact us", contact_index_path(locale: :en), class: "nav-item nav-link" %>
      <%= link_to "Location", maps_path(locale: :en), class: "nav-item nav-link" %>
    </div>
  </div>

</nav>

app/views/contact/_sidebar.fr.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">

  <%= link_to root_path(locale: :fr), class: "navbar-brand" do %>
    <%= image_tag "logo-white2.png", class: 'logo' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Réserver", contact_index_path(locale: :fr), class: "nav-item nav-link" %>
      <%= link_to "Activités", maps_path, class: "nav-item nav-link" %>
    </div>
  </div>

</nav>

app/views/contact/_sidebar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">

  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo-white2.png", class: 'logo' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Réserver", contact_index_path, class: "nav-item nav-link" %>
      <%= link_to "Activités", maps_path, class: "nav-item nav-link" %>
    </div>
  </div>

</nav>

app/views/contact/create.js.erb
// Test for ajax success
console.log("This is the create.js.erb file");
// Render flash message
$('#contact').html("<%= j render 'contact_form' %>");
$('#flash-message').html("<%= j render 'flash' %>").delay(3000).fadeOut(4000);

app/views/contact/index.html.erb
<div id="contact">
	<%= render 'contact_form' %>
</div>

app/views/maps/_sidebar.en.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">

  <%= link_to root_path(locale: :en), class: "navbar-brand" do %>
    <%= image_tag "logo-white2.png", class: 'logo' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Contact us", contact_index_path(locale: :en), class: "nav-item nav-link" %>
      <%= link_to "Location", maps_path(locale: :en), class: "nav-item nav-link" %>
    </div>
  </div>

</nav>

app/views/maps/_sidebar.fr.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">

  <%= link_to root_path(locale: :fr), class: "navbar-brand" do %>
    <%= image_tag "logo-white2.png", class: 'logo' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Réserver", contact_index_path(locale: :fr), class: "nav-item nav-link" %>
      <%= link_to "Activités", maps_path(locale: :fr), class: "nav-item nav-link" %>
    </div>
  </div>

</nav>

app/views/maps/_sidebar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">

  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo-white2.png", class: 'logo' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Réserver", contact_index_path, class: "nav-item nav-link" %>
      <%= link_to "Activités", maps_path, class: "nav-item nav-link" %>
    </div>
  </div>

</nav>

app/views/rooms/_sidebar.en.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">

  <%= link_to root_path(locale: :en), class: "navbar-brand" do %>
    <%= image_tag "logo-white2.png", class: 'logo' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Contact us", contact_index_path(locale: :en), class: "nav-item nav-link" %>
      <%= link_to "Location", maps_path(locale: :en), class: "nav-item nav-link" %>
    </div>
  </div>

</nav>

app/views/rooms/_sidebar.fr.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">

  <%= link_to root_path(locale: :fr), class: "navbar-brand" do %>
    <%= image_tag "logo-white2.png", class: 'logo' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Réserver", contact_index_path(locale: :fr), class: "nav-item nav-link" %>
      <%= link_to "Activités", maps_path(locale: :fr), class: "nav-item nav-link" %>
    </div>
  </div>

</nav>

app/views/rooms/_sidebar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">

  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo-white2.png", class: 'logo' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Réserver", contact_index_path, class: "nav-item nav-link" %>
      <%= link_to "Activités", maps_path, class: "nav-item nav-link" %>
      <%= link_to 'Version française', root_path(locale: :fr), class: "nav-item nav-link" %>
      <%= link_to 'English version', root_path(locale: :en), class: "nav-item nav-link" %>
    </div>
  </div>

</nav>

app/views/rooms/index.en.html.erb
<div class="home_container">

	<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path 'facade1.jpg'%>)">
	  <h1 class='font-weight-light'>Maison Esperluette</h1>
	  <h3 class='text-center'>Bed&Breakfast in a traditional Norman manor</h3>
	</div>


	<div class="container-fluid">
	<div class="row align-items-center justify-content-center">
		<div class="details col-sm-12 col-lg-4 mb-5">
			<div class="block-text__centered text-justify">
				<%= link_to 'Version française  🇫🇷', root_path(locale: :fr), class: "d-flex justify-content-center text-uppercase" %>
				<h3 class="home-title__dark mb-5 mt-5">Experience the charming ambience of Normandy</h3>
				<p class="mr-5 ml-5 mb-3 text-center">Ideally located on the Normandy seashore, close to the town center, Maison Esperluette is a lovely Bed&Breakfast in a stylish setting. Run by an experienced owner, Nathalie, the rooms provide all the amenities of a cosy appartment.
				Each room is individually styled with design decor and traditional comforts.<br>
				Only 10 minutes ride from the sea, the Bed&Breakfast has easy access to all kind of seashore activities: hikes, kite-surf, horseback riding...<br>
			</div>
			<div class="mb-5 mt-5">
				<%= render 'carousel' %>
			</div>
		</div>
	</div>


	<h3 class="home-title__dark mb-5 mt-5">Beautifully furnished rooms</h3>

		<div class="row align-items-center justify-content-center">
			<% @rooms.first(1).each do |room| %>
				<div class="col-sm-12 col-lg-8 ml-1 mb-5">
					<div class="card_room rounded">
						<%= link_to room_path(room, locale: :en), class: "" do %>
							<%= image_tag "grand-gite-chambre.jpg", class: "rounded" %>
							<div class="card-details d-flex flex-column align-items-center justify-content-center">
								<h4 class="mb-2"><%= room.name %></h4>
								<p class="mb-2">Ideal for a family vacation</p>
							</div>
							<%= link_to "Discover the room", room_path(room, locale: :en), class: "btn btn-outline-primary sm mb-4 mt-4" %>
						<% end %>
					</div>
				<% end %>

				<% @rooms.drop(1).each do |room| %>
					<div class="card_room rounded">
						<%= link_to room_path(room, locale: :en), class: "" do %>
							<% if room.name == 'Le petit gîte' %>
								<%= image_tag "petit-gite-fenetre.jpg", class: "rounded" %>
							<% else %>
								<%= image_tag "chambre3.jpg", class: "rounded" %>
							<% end %>
							<div class="card-details d-flex flex-column align-items-center justify-content-center">
								<h4 class="mb-2"><%= room.name %></h4>
								<% if room.name == 'Le petit gîte' %>
									<p class="mb-3">The perfect spot for a seaside weekend</p>
								<% else %>
									<p class="mb-3">Enjoy our spacious suite</p>
								<% end %>
							</div>
							<%= link_to "Discover the room", room_path(room, locale: :en), class: "btn btn-outline-primary sm mb-4 mt-4" %>
						<% end %>
					</div>
				<% end %>
			</div>
		</div>

		<h3 class="home-title__dark mb-5 mt-5">Happy customers!</h3>
		<div class="row align-items-center justify-content-center">
			<div class="col-sm-12 col-lg-8 ml-1 mb-5">
				<%= render 'carousel-reviews' %>
			</div>
		</div>
	</div>


<!-- 	<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(<%#= asset_path 'phare1.jpg'%>)">
	  <h1><%#= link_to "Découvrir la côte d'Albâtre", maps_path, class: "text-center" %></h1>
	</div> -->


</div>

app/views/rooms/index.fr.html.erb
<div class="home_container">

	<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path 'facade1.jpg'%>)">
	  <h1 class='font-weight-light'>Maison Esperluette</h1>
	  <h3 class='text-center'>Gîtes de charme sur la côte normande</h3>
	</div>


	<div class="container-fluid">
	<div class="row align-items-center justify-content-center">
		<div class="details col-sm-12 col-lg-4 mb-5">
			<div class="block-text__centered text-justify">
				<%= link_to 'English version  🇬🇧', root_path(locale: :en), class: "d-flex justify-content-center text-uppercase" %>
				<h3 class="home-title__dark mb-5 mt-5">Le charme discret de la côte normande</h3>
				<p class="mr-5 ml-5 mb-3 text-center">Située en lisière du centre-ville de Cany-Barville, dans un jardin cauchois bien clos de hauts murs, la demeure de maître de Nathalie vous accueille dans un environnement design et chaleureux.<br>
				Ses gîtes spacieux et confortables, sa vaste suite vous garantissent confort et tranquillité.<br>
				À deux heures de Paris, 10 minutes de la côte d’Albâtre, vous serez idéalement placés pour pratiquer : planche à voile, le kite-surf, la randonnée à pied, à cheval ou à vélo...<br>
				…ou simplement vous reposer.</p>
			</div>
			<div class="mb-5 mt-5">
				<%= render 'carousel' %>
			</div>
		</div>
	</div>


	<h3 class="home-title__dark mb-5 mt-5">Des gîtes à 10 minutes de la mer</h3>

		<div class="row align-items-center justify-content-center">
			<% @rooms.first(1).each do |room| %>
				<div class="col-sm-12 col-lg-8 ml-1 mb-5">
					<div class="card_room rounded">
						<%= link_to room_path(room), class: "" do %>
							<%= image_tag "grand-gite-chambre.jpg", class: "rounded" %>
							<div class="card-details d-flex flex-column align-items-center justify-content-center">
								<h4 class="mb-2"><%= room.name %></h4>
								<p class="mb-2">Parfait pour explorer la côte normande en famille</p>
							</div>
							<%= link_to "Découvrir le gîte", room_path(room), class: "btn btn-outline-primary sm mb-4 mt-4" %>
						<% end %>
					</div>
				<% end %>

				<% @rooms.drop(1).each do |room| %>
					<div class="card_room rounded">
						<%= link_to room_path(room), class: "" do %>
							<% if room.name == 'Le petit gîte' %>
								<%= image_tag "petit-gite-fenetre.jpg", class: "rounded" %>
							<% else %>
								<%= image_tag "chambre3.jpg", class: "rounded" %>
							<% end %>
							<div class="card-details d-flex flex-column align-items-center justify-content-center">
								<h4 class="mb-2"><%= room.name %></h4>
								<% if room.name == 'Le petit gîte' %>
									<p class="mb-3">Idéal pour un week-end le long des plages normandes</p>
								<% else %>
									<p class="mb-3">Une grande suite au calme</p>
								<% end %>
							</div>
							<%= link_to "Découvrir le gîte", room_path(room), class: "btn btn-outline-primary sm mb-4 mt-4" %>
						<% end %>
					</div>
				<% end %>
			</div>
		</div>

		<h3 class="home-title__dark mb-5 mt-5">Des avis 100% positifs</h3>
		<div class="row align-items-center justify-content-center">
			<div class="col-sm-12 col-lg-8 ml-1 mb-5">
				<%= render 'carousel-reviews' %>
			</div>
		</div>
	</div>


<!-- 	<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(<%#= asset_path 'phare1.jpg'%>)">
	  <h1><%#= link_to "Découvrir la côte d'Albâtre", maps_path, class: "text-center" %></h1>
	</div> -->


</div>

app/views/rooms/index.html.erb
<div class="home_container">

	<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path 'facade1.jpg'%>)">
	  <h1 class='font-weight-light'>Maison Esperluette</h1>
	  <h3 class='text-center'>Gîtes de charme sur la côte normande</h3>
	</div>


	<div class="container-fluid">
	<div class="row align-items-center justify-content-center">
		<div class="details col-sm-12 col-lg-4 mb-5">
			<div class="block-text__centered text-justify">
				<h3 class="home-title__dark mb-5 mt-5">Le charme discret de la côte normande</h3>
				<p class="mr-5 ml-5 mb-3 text-center">Située en lisière du centre-ville de Cany-Barville, dans un jardin cauchois bien clos de hauts murs, la demeure de maître de Nathalie vous accueille dans un environnement design et chaleureux.<br>
				Ses gîtes spacieux et confortables, sa vaste suite vous garantissent confort et tranquillité.<br>
				À deux heures de Paris, 10 minutes de la côte d’Albâtre, vous serez idéalement placés pour pratiquer : planche à voile, le kite-surf, la randonnée à pied, à cheval ou à vélo...<br>
				…ou simplement vous reposer.</p>
			</div>
			<%#= image_tag "mer1.jpg", class: 'img-round mt-3' %>
			<div class="mb-5 mt-5">
				<%= render 'carousel' %>
			</div>
		</div>
	</div>


	<h3 class="home-title__dark mb-5 mt-5">Des gîtes à 10 minutes de la mer</h3>

		<div class="row align-items-center justify-content-center">
			<% @rooms.first(1).each do |room| %>
				<div class="col-sm-12 col-lg-8 ml-1 mb-5">
					<div class="card_room rounded">
						<%= link_to room_path(room), class: "" do %>
							<%= image_tag "grand-gite-chambre.jpg", class: "rounded" %>
							<div class="card-details d-flex flex-column align-items-center justify-content-center">
								<h4 class="mb-2"><%= room.name %></h4>
								<p class="mb-2">Parfait pour explorer la côte normande en famille</p>
							</div>
							<%= link_to "Découvrir le gîte", room_path(room), class: "btn btn-outline-primary sm mb-4 mt-4" %>
						<% end %>
					</div>
				<% end %>

				<% @rooms.drop(1).each do |room| %>
					<div class="card_room rounded">
						<%= link_to room_path(room), class: "" do %>
							<% if room.name == 'Le petit gîte' %>
								<%= image_tag "petit-gite-fenetre.jpg", class: "rounded" %>
							<% else %>
								<%= image_tag "chambre3.jpg", class: "rounded" %>
							<% end %>
							<div class="card-details d-flex flex-column align-items-center justify-content-center">
								<h4 class="mb-2"><%= room.name %></h4>
								<% if room.name == 'Le petit gîte' %>
									<p class="mb-3">Idéal pour un week-end le long des plages normandes</p>
								<% else %>
									<p class="mb-3">Une grande suite au calme</p>
								<% end %>
							</div>
							<%= link_to "Découvrir le gîte", room_path(room), class: "btn btn-outline-primary sm mb-4 mt-4" %>
						<% end %>
					</div>
				<% end %>
			</div>
		</div>

		<h3 class="home-title__dark mb-5 mt-5">Des avis 100% positifs</h3>
		<div class="row align-items-center justify-content-center">
			<div class="col-sm-12 col-lg-8 ml-1 mb-5">
				<%= render 'carousel-reviews' %>
			</div>
		</div>
	</div>

<!-- 	<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(<%#= asset_path 'phare1.jpg'%>)">
	  <h1><%#= link_to "Découvrir la côte d'Albâtre", maps_path, class: "text-center" %></h1>
	</div> -->


</div>